'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { ShieldCheck, LayoutDashboard, LockKeyhole, UnlockKeyhole, ScanSearch, Boxes, WifiOff } from 'lucide-react'
import { cn } from '@/lib/utils'
const nav = [{ href: '/', label: 'Overview', icon: LayoutDashboard }, { href: '/encrypt', label: 'Encrypt document', icon: LockKeyhole }, { href: '/decrypt', label: 'Recipient decryption', icon: UnlockKeyhole }, { href: '/trace', label: 'Leak trace', icon: ScanSearch }, { href: '/ledger', label: 'Ledger integrity', icon: Boxes }]
export function AppShell({ children }: { children: React.ReactNode }) { const path = usePathname(); return <div className="min-h-screen bg-[#07111f] text-slate-100"><header className="border-b border-slate-800/80 bg-[#081525]/95"><div className="mx-auto flex max-w-7xl items-center justify-between gap-6 px-4 py-4 sm:px-6"><Link href="/" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-cyan-400/10 text-cyan-300 ring-1 ring-cyan-300/20"><ShieldCheck /></span><span><span className="block text-sm font-semibold tracking-wide">VAULTLINE</span><span className="block text-[10px] uppercase tracking-[0.24em] text-slate-500">Forensic watermarking</span></span></Link><div className="flex items-center gap-2 rounded-full border border-slate-700 bg-slate-900/70 px-3 py-1.5 text-xs text-slate-300"><WifiOff className="size-3.5 text-emerald-300" /> Air-gapped mode <span className="size-1.5 rounded-full bg-emerald-400" /></div></div></header><nav className="border-b border-slate-800/70 bg-[#091827]"><div className="mx-auto flex max-w-7xl gap-1 overflow-x-auto px-4 sm:px-6">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={cn('flex shrink-0 items-center gap-2 border-b-2 px-3 py-3 text-sm transition-colors', path === href ? 'border-cyan-400 text-cyan-300' : 'border-transparent text-slate-400 hover:text-slate-100')}><Icon className="size-4" />{label}</Link>)}</div></nav><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:py-10">{children}</main></div> }
export function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.22em] text-cyan-400">{eyebrow}</p><h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{description}</p></div> }
export function Panel({ title, description, children, className }: { title: string; description?: string; children: React.ReactNode; className?: string }) { return <section className={cn('rounded-xl border border-slate-800 bg-[#0c1a2b] shadow-2xl shadow-black/10', className)}><div className="border-b border-slate-800 px-5 py-4"><h2 className="font-medium text-slate-100">{title}</h2>{description && <p className="mt-1 text-xs text-slate-500">{description}</p>}</div><div className="p-5">{children}</div></section> }
export function StatusDot({ good = true }: { good?: boolean }) { return <span className={cn('inline-block size-2 rounded-full', good ? 'bg-emerald-400' : 'bg-rose-400')} /> }
