'use client'

import { useEffect, useState } from 'react'
import { CheckCircle2, RefreshCw, Server, TriangleAlert } from 'lucide-react'
import { AppShell, PageIntro, Panel, StatusDot } from '@/components/app-shell'
import { getLedgerStatus, verifyLedger, type LedgerResponse } from '@/lib/api'

export default function LedgerPage() {
  const [data, setData] = useState<LedgerResponse | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const refresh = async (verify = false) => { setBusy(true); setError(''); try { setData(await (verify ? verifyLedger() : getLedgerStatus())) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Gateway unavailable.') } finally { setBusy(false) } }
  useEffect(() => { void refresh() }, [])
  return <AppShell><PageIntro eyebrow="Integrity controls" title="Ledger integrity" description="Review replica health and independently verify the tamper-evident chain before relying on an attribution result." />{error && <p className="mb-5 text-sm text-rose-300">{error}</p>}{data && !data.quorum_agreement && <div className="mb-6 flex items-center gap-3 rounded-lg border border-rose-400/40 bg-rose-400/10 px-4 py-3 text-sm text-rose-200"><TriangleAlert className="size-5" />Replica divergence detected. New commits may be paused until quorum agreement is restored.</div>}<div className="grid gap-4 md:grid-cols-3">{data?.replicas.map((node) => <div key={node.node_id} className="rounded-xl border border-slate-800 bg-[#0c1a2b] p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Server className="size-4 text-cyan-300" /><span className="font-mono">{node.node_id}</span></div><span className={`inline-flex items-center gap-2 text-xs ${node.online ? 'text-emerald-300' : 'text-rose-300'}`}><StatusDot good={node.online} />{node.online ? 'Online' : 'Offline'}</span></div><div className="mt-7 grid grid-cols-2 gap-4"><div><p className="text-xs text-slate-500">Chain height</p><p className="mt-1 font-mono text-lg">{node.entries ?? '—'}</p></div><div><p className="text-xs text-slate-500">Validation</p><p className="mt-1 flex items-center gap-1 text-sm text-emerald-300">{node.valid ? <><CheckCircle2 className="size-4" />Valid</> : 'Pending'}</p></div></div><p className="mt-5 text-xs text-slate-500">Tip hash</p><p className="mt-1 break-all font-mono text-xs text-cyan-300">{node.tip || 'Unavailable'}</p></div>)}</div><Panel title="Quorum model" description="Why 2-of-3 matters" className="mt-6"><div className="flex flex-col gap-3 text-sm leading-6 text-slate-400"><p>Every attribution record is committed only when two independently controlled replicas agree on the chain tip and signature set.</p><button onClick={() => void refresh(true)} disabled={busy} className="mt-3 inline-flex w-fit items-center gap-2 rounded-lg bg-cyan-300 px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50"><RefreshCw className={busy ? 'size-4 animate-spin' : 'size-4'} />{busy ? 'Verifying…' : 'Verify ledger integrity'}</button></div></Panel></AppShell>
}
